### ISSUE TITLE
it would be nice to combine pkg rename with pkg list in my opinion

### ISSUE THREAD

**Issue by mtnjustme** [n1ghty/pkg_rename#1]
title, check all sub folders, change all names etc, or just improving this version to check for folders as well as files, if a folder is mentioned instead of a file.

**Comment by n1ghty** [comment]
extended formatting and multi file renaming are already planed features :)

**Comment by n1ghty** [comment]
I have just released pkg_tools. It's a collection of PS4 PKG tools which currently consists of the pkg_list and pkg_rename tools. The tools have been improved significantly with a lot of options. E.g. custom name formatting. https://github.com/n1ghty/pkg_tools
